CREATE DATABASE IF NOT EXISTS jira_db;
USE jira_db;
CREATE TABLE IF NOT EXISTS jira_table (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT primary key,
    `date` DATE NOT NULL,
    `data_type` VARCHAR(50) NOT NULL,
    `value` FLOAT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME
);
